package(default_visibility = ["//visibility:public"])

exports_files(["graph_params.h"])

cc_library(
    name = "didagle",
    hdrs = [
        "didagle.h",
    ],
    deps = [
        "//didagle/store",
    ],
)
