package(default_visibility = ["//visibility:public"])

exports_files(["graph_params.h"])

cc_library(
    name = "event",
    srcs = [
        "event.cpp",
    ],
    hdrs = [
        "event.h",
    ],
)
