package(default_visibility = ["//visibility:public"])

exports_files(["graph_params.h"])

cc_library(
    name = "log",
    srcs = [
        "log.cpp",
    ],
    hdrs = [
        "log.h",
    ],
    deps = [
        "@spdlog",
    ],
)
