package(default_visibility = ["//visibility:public"])

exports_files(["graph_params.h"])

cc_library(
    name = "processor_dump",
    srcs = [
        "processor_dump.cpp",
    ],
    deps = [
        "//didagle/processor",
    ],
)
